In [1]:
import numpy as np

#### Задание 1

In [2]:
a = np.array([[1,6], [2,8], [3,11], [3,10], [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [25]:
mean_a = a.mean(axis = 0)

array([2. , 8.4])

#### Задание 2

In [28]:
a_centered = a - mean_a

#### Задание 3

In [34]:
a_centered_sp = a_centered[0][0]*a_centered[0][1]+a_centered[1][0]*a_centered[1][1]+a_centered[2][0]*a_centered[2][1]+a_centered[3][0]*a_centered[3][1]+a_centered[4][0]*a_centered[4][1]

In [37]:
a.shape

(5, 2)

In [38]:
a_centered_sp / (5 - 1)

2.0

#### Задание 4

In [43]:
m = a.T

In [44]:
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [45]:
np.cov(m)

array([[1. , 2. ],
       [2. , 4.3]])